version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          command: echo "Hello!" 

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - run: 
          name: Deployment
          command: echo "Success!" 

workflows:
  build-hold-deploy:
    jobs:
      - build
      - hold:
          type: approval # 承認ジョブを表示。
          requires:
            - build
      - hold2:
          context: approvers # ここで制限付きコンテキストを参照。
          type: approval # 承認ジョブを表示。
          requires:
            - hold
      - deploy:
          context: 2nd_approvers # ここで制限付きコンテキストを参照。
          requires:
            - hold2
